name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install gym
        pip install -r requirements.txt
        pip install gdown
    
    - name: 3. Downloading weights
      run: gdown 1P3mY2cLpECJdw_bRzpAm4GK1O9qSTw7s -O ntuple_weights.pkl

    - name: 3.5. list the working directory
      run: |
        echo "=============================="
        ls -la
        echo "=============================="

    - name: 4. Ensure env.so is executable
      run: chmod +x env.cpython-38-x86_64-linux-gnu.so

    - name: 5. Run Evaluation
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47
